# Generated by Django 3.2 on 2021-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('reg', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('year', models.FloatField()),
            ],
        ),
    ]
